apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dinghy-ping.fullname" . }}
  labels:
    app: {{ include "dinghy-ping.name" . }}
    chart: {{ include "dinghy-ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dinghy-ping.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "dinghy-ping.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "dinghy-ping.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local
            - name: DINGHY_PING_HOST
              value: {{ .Release.Name }}.{{- .Values.subdomain }}
            - name: DD_DOGSTATSD_DISABLE
              value: "{{ .Values.disable_dogstatsd }}"
            - name: MY_CLUSTER_DOMAIN 
              value: {{ .Values.subdomain }}
            - name: MY_APP_NAME
              value: {{ .Release.Name }} 
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: metrics 
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
