{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dinghy-ping.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "dinghy-ping.name" . }}
    chart: {{ include "dinghy-ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.{{- .Values.ingress.subdomain }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Release.Name }}.{{- .Values.ingress.subdomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "dinghy-ping.fullname" . }}
              servicePort: http
{{- end }}
