{{- if .Values.nginxIngress.enabled -}}
{{- $fullName := include "dinghy-ping.fullname" . -}}
{{- $ingressPath := .Values.nginxIngress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "dinghy-ping.name" . }}
    chart: {{ include "dinghy-ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.nginxIngress.sslRedirect }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- end }}
spec:
  ingressClassName: {{ .Values.nginxIngress.className }}
{{- if .Values.nginxIngress.tls }}
  tls:
  {{- range .Values.nginxIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Release.Name }}.{{- .Values.subdomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "dinghy-ping.fullname" . }}
              servicePort: http
{{- end }}
