print("Dinghy Ping!")
local_resource("lint", ["poetry", "run", "flake8", "."])
local_resource("black", ["poetry", "run", "black", "--check", "."])
local_resource("isort", ["poetry", "run", "isort", "--check-only", "."])
docker_build('dinghy-ping', '.')
k8s_yaml('local_development_scripts/local.yaml')
k8s_resource('dinghy-ping', port_forwards=8080)
k8s_resource('dinghy-ping-redis', port_forwards=6379)
