print("Dinghy Ping!")
local_resource("lint", ["pipenv", "run", "flake8", "dinghy_ping"])
docker_build('dinghy-ping', '.')
k8s_yaml('local_development_scripts/local.yaml')
k8s_resource('dinghy-ping', port_forwards=8080)
k8s_resource('dinghy-ping-redis', port_forwards=6379)