replicaCount: 1 
nameOverride: dinghy-ping-beta

image:
  repository: sepulworld/dinghy-ping
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

nginxIngress:
  enabled: true
  className: nginx
  sslRedirect: true
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  subdomain: voltron.cloud

istioVirtualService:
  enabled: false
  # gateways:
  #  - istio-gateways/private-gateway
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  subdomain: voltron.cloud

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

redisStorageSize: 2Gi
