replicaCount: 1

image:
  repository: sepulworld/dinghy-ping
  tag: latest
  pullPolicy: Always

# input your subdomain here
subdomain: voltron.cloud
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

nginxIngress:
  enabled: false
  className: nginx
  sslRedirect: true
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

istioVirtualService:
  enabled: false
  gateways: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

redisStorageSize: 2Gi
